def next_state(state, token):
    if state=='X':
        return 'X'#stays in X
    if state=='O':
        if token.startswith('{'):
            if token.endswith('}'):
                return 'U'
            return 'B'
        if token.endswith('}'):
            return 'X'
        return 'O'
    if state=='B':
        if token.startswith('{'):
            return 'X'
        if token.endswith('}'):
            return 'L'
        return 'I'
    if state=='I':
        if token.startswith('{'):
            return 'X'
        if token.endswith('}'):
            return 'L'
        return 'I'
    if state=='L':
        if token.startswith('{'):
            if token.endswith('}'):
                return 'U'
            return 'B'
        if token.endswith('}'):
            return 'X'
        return 'O'
    if state=='U':
        if token.startswith('{'):
            if token.endswith('}'):
                return 'U'
            return 'B'
        if token.endswith('}'):
            return 'X'
        return 'O'
